# Generated by Django 2.0.6 on 2018-06-07 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='nom',
        ),
        migrations.AddField(
            model_name='user',
            name='civilite',
            field=models.CharField(choices=[('Mme', 'Madame'), ('M.', 'Monsieur'), ('Dr', 'Docteur'), ('Pr', 'Professeur')], default='M.', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='fonction',
            field=models.CharField(default='comptable', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(default=999999999, help_text="numero de téléphone à 9 chiffres, l'indicatif est optionnel", max_length=16, validators=[django.core.validators.RegexValidator(message='le format du numéro de téléphone est:[(+000) ]999999999;la partie entre crochet est optionnel. exemple: (+237) 674228621, 674228621, (+234)674228621', regex='^(\\(\\+\\d{0,3}\\))? ?\\d{9}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
