# Generated by Django 2.0.6 on 2018-06-07 12:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180607_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('denomination', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Dénomination')),
                ('sigle', models.CharField(blank=True, max_length=10)),
                ('marche', models.CharField(blank=True, max_length=200, verbose_name="Domaine d'activité")),
                ('ville_siege', models.CharField(max_length=25, verbose_name='ville siège')),
                ('adresse_physique', models.CharField(help_text='Rue, quartier, lieu-dit', max_length=200)),
                ('adresse_postale', models.CharField(blank=True, max_length=32)),
                ('telephone', models.CharField(default='(+237) 000000000', help_text="L'indicatif est optionnel. exemple: (+237) 694484246", max_length=16, validators=[django.core.validators.RegexValidator(message='le format du numéro de téléphone est:[(+000) ]999999999;la partie entre crochet est optionnel. exemple: (+237) 674228621, 674228621, (+234)674228621', regex='^(\\(\\+\\d{0,3}\\))? ?\\d{9}$')])),
                ('bu_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b_units_manages', to=settings.AUTH_USER_MODEL, verbose_name="Directeur de l'entité")),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='users.BusinessUnit'),
        ),
    ]
