# Generated by Django 2.0.6 on 2018-06-07 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180607_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nom',
        ),
        migrations.AlterField(
            model_name='user',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='users.BusinessUnit'),
        ),
    ]
