# Generated by Django 2.0.6 on 2018-06-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180607_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='denomination',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Dénomination'),
        ),
    ]
