# Generated by Django 2.0.6 on 2018-06-08 10:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180607_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessunit',
            options={'verbose_name_plural': 'Business Units'},
        ),
        migrations.RemoveField(
            model_name='businessunit',
            name='bu_manager',
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='adresse_postale',
            field=models.CharField(blank=True, max_length=32, verbose_name='Adresse postale'),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='denomination',
            field=models.CharField(help_text='Nom de la société ou du projet', max_length=100, primary_key=True, serialize=False, verbose_name='Dénomination'),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='sigle',
            field=models.CharField(blank=True, help_text='exemple: C.T.C', max_length=10),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='telephone',
            field=models.CharField(default='(+237) 000 000 000', help_text="L'indicatif est optionnel. exemple: (+237) 694484246", max_length=18, validators=[django.core.validators.RegexValidator(message='le format du numéro de téléphone est:[(+000) ]999999999;la partie entre crochet est optionnel. exemple: (+237) 674228621, 674228621, (+234)674228621', regex='^(\\(\\+\\d{0,3}\\))? ?\\d{9}$')], verbose_name='Numero de Téléphone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='users.BusinessUnit', verbose_name='Business Unit'),
        ),
        migrations.AlterField(
            model_name='user',
            name='civilite',
            field=models.CharField(choices=[('Mme', 'Madame'), ('M.', 'Monsieur'), ('Dr', 'Docteur'), ('Pr', 'Professeur')], default='M.', max_length=3, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fonction',
            field=models.CharField(help_text='exemple: Directeur général', max_length=100, verbose_name='poste'),
        ),
    ]
