# Generated by Django 2.0.6 on 2018-06-08 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180608_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='users.BusinessUnit', verbose_name='Business Unit'),
        ),
    ]
