# Generated by Django 2.0.6 on 2018-06-11 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180608_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='telephone',
            field=models.CharField(default='(+237) 000000000', help_text="L'indicatif est optionnel. exemple: (+237) 694484246", max_length=18, validators=[django.core.validators.RegexValidator(message='le format du numéro de téléphone est:[(+000) ]999999999;la partie entre crochet est optionnel. exemple: (+237) 674228621, 674228621, (+234)674228621', regex='^(\\(\\+\\d{0,3}\\))? ?\\d{9}$')], verbose_name='Numero de Téléphone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
    ]
