# Generated by Django 2.0.6 on 2018-06-12 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20180611_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessunit',
            options={'ordering': ('denomination',), 'verbose_name_plural': 'Business Units'},
        ),
        migrations.AddField(
            model_name='businessunit',
            name='projet',
            field=models.BooleanField(default=False, help_text='Le business unit est-il un projet?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='users.BusinessUnit', verbose_name='Business Unit'),
        ),
    ]
