# Generated by Django 2.0.6 on 2018-06-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_businessunit_site_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='site_web',
            field=models.URLField(blank=True, null=True, verbose_name='site internet'),
        ),
    ]
