# Generated by Django 2.0.6 on 2018-07-27 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20180725_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='telephone',
            field=models.CharField(default='(+237) 000000000', help_text="L'indicatif est optionnel. exemple: (+237) 694484246", max_length=18, validators=[django.core.validators.RegexValidator(message='le format du numéro de téléphone est:[(+000)][ ]000000000;les parties entre crochet sont optionnelles. exemple: (+237) 674228621, 674228621, (+234)674228621', regex='^(\\(\\+\\d{0,3}\\))? ?\\d{9}$')], verbose_name='Numero de Téléphone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(help_text="numero de téléphone à 9 chiffres, l'indicatif est optionnel", max_length=18, validators=[django.core.validators.RegexValidator(message='le format du numéro de téléphone est:[(+000)][ ]000000000;les parties entre crochet sont optionnelles. exemple: (+237) 674228621, 674228621, (+234)674228621', regex='^(\\(\\+\\d{0,3}\\))? ?\\d{9}$')]),
        ),
    ]
