# Generated by Django 2.0.6 on 2018-08-23 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20180727_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=30, verbose_name='poste')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.BusinessUnit')),
            ],
            options={
                'ordering': ('poste',),
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_unit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fonction',
        ),
        migrations.AlterField(
            model_name='user',
            name='civilite',
            field=models.CharField(choices=[('Mme', 'Madame'), ('M.', 'Monsieur'), ('Dr', 'Docteur'), ('Pr', 'Professeur')], default='M.', max_length=3, verbose_name='titre'),
        ),
        migrations.AddField(
            model_name='position',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postes', to=settings.AUTH_USER_MODEL, verbose_name='Employé(e)'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='employes',
            field=models.ManyToManyField(related_name='business_unit', through='users.Position', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('poste', 'employe', 'business_unit')},
        ),
    ]
