# Generated by Django 2.0.6 on 2018-08-25 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20180824_1154'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('employe', 'business_unit')},
        ),
    ]
