# Generated by Django 2.0.6 on 2018-10-08 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20180825_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='employes',
            field=models.ManyToManyField(related_name='business_units', through='users.Position', to=settings.AUTH_USER_MODEL),
        ),
    ]
