# Generated by Django 2.0.6 on 2018-10-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20181008_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='raison_sociale',
            field=models.CharField(default='raison sociale', max_length=50, verbose_name='raison sociale'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='denomination',
            field=models.CharField(help_text='Nom de la société ou du projet; doit être unique.', max_length=100, primary_key=True, serialize=False, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='marche',
            field=models.CharField(blank=True, help_text="activités de l'entrepriser / but du projet", max_length=200, verbose_name='objet'),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='ville_siege',
            field=models.CharField(max_length=25, verbose_name='ville'),
        ),
    ]
