# Generated by Django 2.0.6 on 2018-10-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20181012_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='raison_sociale',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='raison sociale'),
        ),
    ]
