# Generated by Django 2.0.6 on 2018-11-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20181012_1242'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('employe', 'business_unit', 'poste')},
        ),
    ]
