# Generated by Django 2.0.6 on 2018-11-23 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20181123_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessunit',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uuid',
        ),
    ]
