# Generated by Django 2.0.6 on 2019-01-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20181123_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='poste',
            field=models.CharField(max_length=50, verbose_name='poste'),
        ),
    ]
