# Generated by Django 2.0.6 on 2019-01-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20190121_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='ville_siege',
            field=models.CharField(max_length=100, verbose_name='ville'),
        ),
    ]
