# Generated by Django 2.0.6 on 2018-06-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('denomination', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Dénomination')),
                ('sigle', models.CharField(blank=True, max_length=10)),
                ('marche', models.CharField(blank=True, max_length=200, verbose_name="Domaine d'activité")),
                ('ville_siege', models.CharField(max_length=25, verbose_name='ville siège')),
                ('adresse_physique', models.CharField(help_text='Rue, quartier, lieu-dit', max_length=200)),
                ('adresse_postale', models.CharField(blank=True, max_length=32)),
            ],
        ),
    ]
