# Generated by Django 2.0.6 on 2018-06-13 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0013_auto_20180613_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonneesProcessus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Processus',
            fields=[
                ('code_processus', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_processus', models.CharField(choices=[('PM', 'Processus de management'), ('PO', 'Processus opérationnel'), ('PS', 'Processus de soutien')], default='PO', max_length=2, verbose_name='Type de Processus')),
                ('nom', models.CharField(db_index=True, max_length=50, verbose_name='Nom')),
                ('description', models.CharField(max_length=300)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.BusinessUnit', verbose_name='Propriétaire')),
                ('proc_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processus_manages', to=settings.AUTH_USER_MODEL, verbose_name='manager du processus')),
            ],
            options={
                'verbose_name_plural': 'processus',
            },
        ),
        migrations.AddField(
            model_name='donneesprocessus',
            name='processus1',
            field=models.ForeignKey(blank=True, help_text='Laisser vide si origine externe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ouput_data', to='risk_register.Processus', verbose_name='Origine'),
        ),
        migrations.AddField(
            model_name='donneesprocessus',
            name='processus2',
            field=models.ForeignKey(blank=True, help_text='Laisser vide si destination externe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input_data', to='risk_register.Processus', verbose_name='Destination'),
        ),
        migrations.AlterUniqueTogether(
            name='donneesprocessus',
            unique_together={('nom', 'processus2'), ('nom', 'processus1')},
        ),
    ]
