# Generated by Django 2.0.6 on 2018-06-15 08:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activiterisque',
            name='verifie',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default=0, max_length=100, no_check_for_status=True, verbose_name='vérication'),
        ),
        migrations.AddField(
            model_name='processdata',
            name='commentaire',
            field=models.TextField(blank=True, help_text='Veuillez indiquer le nom du partenaire externe                                                si origine ou destination externe', max_length=255, verbose_name='commentaires'),
        ),
        migrations.AddField(
            model_name='processusrisque',
            name='verifie',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default=0, max_length=100, no_check_for_status=True, verbose_name='vérication'),
        ),
        migrations.AlterField(
            model_name='activiterisque',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 15, 8, 53, 35, 463816, tzinfo=utc), verbose_name='revue prévue pour le: '),
        ),
        migrations.AlterField(
            model_name='controle',
            name='critere_cible',
            field=models.CharField(choices=[('S', 'Sévérité'), ('O', 'Occurence'), ('D', 'Détectabilité')], default='O', max_length=1, verbose_name='critère cible'),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 14, 8, 53, 35, 479416, tzinfo=utc), verbose_name='revue prevue pour le'),
        ),
        migrations.AlterField(
            model_name='processusrisque',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 15, 8, 53, 35, 463816, tzinfo=utc), verbose_name='revue prévue pour le: '),
        ),
    ]
