# Generated by Django 2.0.6 on 2018-06-07 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessUnit',
        ),
    ]
