# Generated by Django 2.0.6 on 2018-06-13 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donneesprocessus',
            name='processus1',
            field=models.ForeignKey(blank=True, help_text="Laisser vide si origine externe à l'entreprise", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ouput_data', to='risk_register.Processus', verbose_name='Origine'),
        ),
        migrations.AlterField(
            model_name='donneesprocessus',
            name='processus2',
            field=models.ForeignKey(blank=True, help_text="Laisser vide si destination externe à l'entreprise", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input_data', to='risk_register.Processus', verbose_name='Destination'),
        ),
    ]
