# Generated by Django 2.0.6 on 2018-06-23 09:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0002_auto_20180619_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activite',
            options={'ordering': ('nom',), 'verbose_name': 'Activité', 'verbose_name_plural': 'activités'},
        ),
        migrations.AlterField(
            model_name='activite',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='pendind', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='activiterisque',
            name='criterisation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='risk_register.CritereDuRisque', verbose_name='Seuil de risque'),
        ),
        migrations.AlterField(
            model_name='activiterisque',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 23, 9, 41, 40, 405220, tzinfo=utc), verbose_name='revue prévue pour le: '),
        ),
        migrations.AlterField(
            model_name='controle',
            name='critere_cible',
            field=models.CharField(choices=[('D', 'Détectabilité'), ('S', 'Sévérité'), ('O', 'Occurence')], default='O', max_length=1, verbose_name='critère cible'),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 22, 9, 41, 40, 420820, tzinfo=utc), verbose_name='revue prevue pour le'),
        ),
        migrations.AlterField(
            model_name='processdata',
            name='commentaire',
            field=models.CharField(blank=True, help_text="Veuillez indiquer le nom de l'origine  externe", max_length=255, verbose_name='commentaires'),
        ),
        migrations.AlterField(
            model_name='processusrisque',
            name='criterisation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='risk_register.CritereDuRisque', verbose_name='Seuil de risque'),
        ),
        migrations.AlterField(
            model_name='processusrisque',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 23, 9, 41, 40, 405220, tzinfo=utc), verbose_name='revue prévue pour le: '),
        ),
    ]
