# Generated by Django 2.0.6 on 2018-06-23 09:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0003_auto_20180623_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activiterisque',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 23, 9, 48, 9, 379423, tzinfo=utc), verbose_name='revue prévue pour le: '),
        ),
        migrations.AlterField(
            model_name='controle',
            name='critere_cible',
            field=models.CharField(choices=[('S', 'Sévérité'), ('O', 'Occurence'), ('D', 'Détectabilité')], default='O', max_length=1, verbose_name='critère cible'),
        ),
        migrations.AlterField(
            model_name='criteredurisque',
            name='detectabilite',
            field=models.SmallIntegerField(choices=[(1, '1-Détection permanente'), (2, '2-Détection élevée'), (3, '3-Moyenne'), (4, '4-Très basse'), (5, '5-Capacité minime'), (6, '6-Incapacité de détection')], default=3, verbose_name='détectabilité'),
        ),
        migrations.AlterField(
            model_name='criteredurisque',
            name='occurence',
            field=models.SmallIntegerField(choices=[(1, '1-Quasi impossible'), (2, '2-Très improbable'), (3, '3-Improbable'), (4, '4-Probable'), (5, '5-Très probable'), (6, '6-Quasi certain')], default=3, verbose_name='ocurrence'),
        ),
        migrations.AlterField(
            model_name='criteredurisque',
            name='severite',
            field=models.SmallIntegerField(choices=[(1, '1-Faible'), (2, '2-Moyenne'), (3, '3-Sérieux'), (4, '4-Grave'), (5, '5-Très Grave'), (6, '6-Catastrophique')], default=3, verbose_name='sévérité'),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 22, 9, 48, 9, 395023, tzinfo=utc), verbose_name='revue prevue pour le'),
        ),
        migrations.AlterField(
            model_name='processusrisque',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 23, 9, 48, 9, 379423, tzinfo=utc), verbose_name='revue prévue pour le: '),
        ),
    ]
