# Generated by Django 2.0.6 on 2018-06-18 09:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0004_auto_20180615_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activiterisque',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 18, 9, 53, 0, 404229, tzinfo=utc), verbose_name='revue prévue pour le: '),
        ),
        migrations.AlterField(
            model_name='controle',
            name='critere_cible',
            field=models.CharField(choices=[('S', 'Sévérité'), ('D', 'Détectabilité'), ('O', 'Occurence')], default='O', max_length=1, verbose_name='critère cible'),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 17, 9, 53, 0, 404229, tzinfo=utc), verbose_name='revue prevue pour le'),
        ),
        migrations.AlterField(
            model_name='processdata',
            name='commentaire',
            field=models.CharField(blank=True, help_text='Veuillez indiquer le nom du partenaire externe                                                si origine ou destination externe', max_length=255, verbose_name='commentaires'),
        ),
        migrations.AlterField(
            model_name='processusrisque',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 18, 9, 53, 0, 404229, tzinfo=utc), verbose_name='revue prévue pour le: '),
        ),
    ]
