# Generated by Django 2.0.6 on 2018-06-25 11:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('risk_register', '0004_auto_20180623_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='controle',
            name='assigne_a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traitement_assignes', to=settings.AUTH_USER_MODEL, verbose_name='assigné à'),
        ),
        migrations.AlterField(
            model_name='activiterisque',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 25, 11, 25, 11, 460238, tzinfo=utc), verbose_name='revue prévue pour le: '),
        ),
        migrations.AlterField(
            model_name='controle',
            name='critere_cible',
            field=models.CharField(choices=[('O', 'Occurence'), ('D', 'Détectabilité'), ('S', 'Sévérité')], default='O', max_length=1, verbose_name='critère cible'),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 24, 11, 25, 11, 465238, tzinfo=utc), verbose_name='revue prevue pour le'),
        ),
        migrations.AlterField(
            model_name='processusrisque',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 25, 11, 25, 11, 460238, tzinfo=utc), verbose_name='revue prévue pour le: '),
        ),
    ]
