# Generated by Django 2.0.6 on 2018-06-18 12:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0005_auto_20180618_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criteredurisque',
            options={'verbose_name': 'Critérisation'},
        ),
        migrations.AlterField(
            model_name='activiterisque',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 18, 12, 0, 43, 579965, tzinfo=utc), verbose_name='revue prévue pour le: '),
        ),
        migrations.AlterField(
            model_name='controle',
            name='critere_cible',
            field=models.CharField(choices=[('O', 'Occurence'), ('S', 'Sévérité'), ('D', 'Détectabilité')], default='O', max_length=1, verbose_name='critère cible'),
        ),
        migrations.AlterField(
            model_name='controle',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default=0, max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 17, 12, 0, 43, 583965, tzinfo=utc), verbose_name='revue prevue pour le'),
        ),
        migrations.AlterField(
            model_name='processusrisque',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 18, 12, 0, 43, 579965, tzinfo=utc), verbose_name='revue prévue pour le: '),
        ),
    ]
