# Generated by Django 2.0.6 on 2018-06-29 07:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0006_auto_20180628_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controle',
            options={'get_latest_by': 'created', 'ordering': ('start',), 'verbose_name': 'contrôle', 'verbose_name_plural': 'contrôles'},
        ),
        migrations.AlterModelOptions(
            name='criteredurisque',
            options={'verbose_name': 'critérisation', 'verbose_name_plural': 'critérisation'},
        ),
        migrations.AlterModelOptions(
            name='processus',
            options={'verbose_name': 'processus', 'verbose_name_plural': 'processus'},
        ),
        migrations.AlterModelOptions(
            name='risque',
            options={'ordering': ('description',), 'verbose_name': 'risque', 'verbose_name_plural': 'risques'},
        ),
        migrations.AlterField(
            model_name='activiterisque',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 29, 7, 4, 7, 402120, tzinfo=utc), verbose_name='revue prévue pour le: '),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 28, 7, 4, 7, 408117, tzinfo=utc), verbose_name='revue prevue pour le'),
        ),
        migrations.AlterField(
            model_name='processusrisque',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 29, 7, 4, 7, 402120, tzinfo=utc), verbose_name='revue prévue pour le: '),
        ),
    ]
