# Generated by Django 2.0.6 on 2018-06-29 09:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0007_auto_20180629_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activiterisque',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 29, 9, 14, 13, 212738, tzinfo=utc), verbose_name='revue prévue pour le: '),
        ),
        migrations.AlterField(
            model_name='activiterisque',
            name='verifie',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='pending', max_length=100, no_check_for_status=True, verbose_name='vérification'),
        ),
        migrations.AlterField(
            model_name='controle',
            name='critere_cible',
            field=models.CharField(choices=[('O', 'Occurence'), ('S', 'Sévérité'), ('D', 'Détectabilité')], default='O', max_length=1, verbose_name='critère cible'),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 28, 9, 14, 13, 216738, tzinfo=utc), verbose_name='revue prevue pour le'),
        ),
        migrations.AlterField(
            model_name='processusrisque',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 29, 9, 14, 13, 212738, tzinfo=utc), verbose_name='revue prévue pour le: '),
        ),
        migrations.AlterField(
            model_name='processusrisque',
            name='verifie',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='pending', max_length=100, no_check_for_status=True, verbose_name='vérification'),
        ),
    ]
