# Generated by Django 2.0.6 on 2018-06-30 09:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0008_auto_20180629_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activiterisque',
            options={'get_latest_by': 'created', 'ordering': ('-created', 'verifie_le'), 'verbose_name': "risque de l'activité", 'verbose_name_plural': 'risques des activités'},
        ),
        migrations.AlterField(
            model_name='activiterisque',
            name='date_revue',
            field=models.DateTimeField(blank=True, null=True, verbose_name='revue'),
        ),
        migrations.AlterField(
            model_name='controle',
            name='critere_cible',
            field=models.CharField(choices=[('O', 'Occurence'), ('D', 'Détectabilité'), ('S', 'Sévérité')], default='O', max_length=1, verbose_name='critère cible'),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 29, 9, 42, 2, 710922, tzinfo=utc), verbose_name='revue prevue pour le'),
        ),
        migrations.AlterField(
            model_name='processusrisque',
            name='date_revue',
            field=models.DateTimeField(blank=True, null=True, verbose_name='revue'),
        ),
    ]
