# Generated by Django 2.0.6 on 2018-07-02 17:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0010_auto_20180630_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='critere_cible',
            field=models.CharField(choices=[('D', 'Détectabilité'), ('S', 'Sévérité'), ('O', 'Occurence')], default='O', max_length=1, verbose_name='critère cible'),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 31, 17, 19, 56, 117898, tzinfo=utc), verbose_name='revue prevue pour le'),
        ),
        migrations.AlterField(
            model_name='processdata',
            name='commentaire',
            field=models.CharField(blank=True, help_text="Veuillez indiquer le nom de l'origine  externe", max_length=255, verbose_name='fournisseur externe'),
        ),
        migrations.AlterField(
            model_name='processdata',
            name='origine',
            field=models.ForeignKey(blank=True, help_text="Laisser vide si origine externe à l'entreprise", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ouput_data', to='risk_register.Processus', verbose_name='fournisseur interne'),
        ),
        migrations.AlterField(
            model_name='processus',
            name='input_data',
            field=models.ManyToManyField(blank=True, null=True, related_name='clients', to='risk_register.ProcessData', verbose_name="Données d'entrée"),
        ),
    ]
