# Generated by Django 2.0.6 on 2018-07-02 18:06

import datetime
from django.db import migrations, models
import django.db.models.expressions
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0012_auto_20180702_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='critere_cible',
            field=models.CharField(choices=[('S', 'Sévérité'), ('O', 'Occurence'), ('D', 'Détectabilité')], default='O', max_length=1, verbose_name='critère cible'),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 31, 18, 6, 39, 276190, tzinfo=utc), verbose_name='revue prevue pour le'),
        ),
        migrations.AlterField(
            model_name='processus',
            name='input_data',
            field=models.ManyToManyField(limit_choices_to=models.Q(_negated=True, origine__code_processus=django.db.models.expressions.F('code_processus')), related_name='clients', to='risk_register.ProcessData', verbose_name="Données d'entrée"),
        ),
    ]
