# Generated by Django 2.0.6 on 2018-07-25 10:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0015_auto_20180702_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='pending', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='controle',
            name='nom',
            field=models.CharField(max_length=300, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='controle',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='in_progress', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 23, 10, 25, 2, 268880, tzinfo=utc), verbose_name='revue prevue pour le'),
        ),
    ]
