# Generated by Django 2.0.6 on 2018-07-27 09:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('risk_register', '0016_auto_20180725_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='activiterisque',
            name='suivi_par',
            field=models.ManyToManyField(related_name='activiterisques_suivis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controle',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='détail'),
        ),
        migrations.AddField(
            model_name='controle',
            name='est_approuve',
            field=models.BooleanField(default=False, verbose_name='approuvé'),
        ),
        migrations.AddField(
            model_name='controle',
            name='est_validide',
            field=models.BooleanField(default=False, verbose_name='validé'),
        ),
        migrations.AddField(
            model_name='processusrisque',
            name='suivi_par',
            field=models.ManyToManyField(related_name='processusrisques_suivis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='controle',
            name='assigne_a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traitements_assignes', to=settings.AUTH_USER_MODEL, verbose_name='assigné à'),
        ),
        migrations.AlterField(
            model_name='controle',
            name='critere_cible',
            field=models.CharField(choices=[('D', 'Détectabilité'), ('O', 'Occurence'), ('S', 'Sévérité')], default='O', max_length=1, verbose_name='critère cible'),
        ),
        migrations.AlterField(
            model_name='controle',
            name='nom',
            field=models.CharField(max_length=50, verbose_name='intitulé'),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 25, 9, 13, 46, 598884, tzinfo=utc), verbose_name='revue prevue pour le'),
        ),
    ]
