# Generated by Django 2.0.6 on 2018-08-06 13:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0018_auto_20180727_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controle',
            old_name='est_validide',
            new_name='est_valide',
        ),
        migrations.AlterField(
            model_name='controle',
            name='critere_cible',
            field=models.CharField(choices=[('D', 'Détectabilité'), ('O', 'Occurence'), ('S', 'Sévérité')], default='O', max_length=1, verbose_name='critère cible'),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 5, 13, 17, 25, 657463, tzinfo=utc), verbose_name='revue prevue pour le'),
        ),
    ]
