# Generated by Django 2.0.6 on 2018-08-21 14:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0019_auto_20180806_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='risque',
            options={'ordering': ('nom', 'description'), 'verbose_name': 'risque', 'verbose_name_plural': 'risques'},
        ),
        migrations.AlterField(
            model_name='controle',
            name='acheve_le',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', when={'completed'}),
        ),
        migrations.AlterField(
            model_name='controle',
            name='critere_cible',
            field=models.CharField(choices=[('S', 'Sévérité'), ('D', 'Détectabilité'), ('O', 'Occurence')], default='O', max_length=1, verbose_name='critère cible'),
        ),
        migrations.AlterField(
            model_name='criteredurisque',
            name='detectabilite',
            field=models.SmallIntegerField(choices=[(1, 'Détection permanente'), (2, 'Détection élevée'), (3, 'Moyenne'), (4, 'Très basse'), (5, 'Capacité minime'), (6, 'Incapacité de détection')], default=3, verbose_name='détectabilité'),
        ),
        migrations.AlterField(
            model_name='criteredurisque',
            name='severite',
            field=models.SmallIntegerField(choices=[(1, '1-Faible'), (2, '2-Moyenne'), (3, '3-Important'), (4, '4-Elevé'), (5, '5-Très elevé'), (6, '6-Maximal')], default=3, verbose_name='impact'),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 20, 14, 40, 15, 865363, tzinfo=utc), verbose_name='revue prevue pour le'),
        ),
        migrations.AlterField(
            model_name='processdata',
            name='commentaire',
            field=models.CharField(blank=True, help_text="Veuillez indiquer le nom de l'origine  externe ou laisser vide siorigine interne", max_length=255, null=True, verbose_name='fournisseur externe'),
        ),
    ]
