# Generated by Django 2.0.6 on 2018-08-21 14:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0020_auto_20180821_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimation',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 20, 14, 59, 35, 221674, tzinfo=utc), verbose_name='revue prevue pour le'),
        ),
    ]
