# Generated by Django 2.0.6 on 2018-08-23 11:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0021_auto_20180821_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processusrisque',
            options={'get_latest_by': 'created', 'ordering': ('-created', 'verifie_le'), 'verbose_name': 'risque du processus', 'verbose_name_plural': 'risques des processus'},
        ),
        migrations.AlterField(
            model_name='estimation',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 22, 11, 34, 22, 417755, tzinfo=utc), verbose_name='revue prevue pour le'),
        ),
        migrations.AlterField(
            model_name='processdata',
            name='commentaire',
            field=models.CharField(blank=True, help_text="Veuillez indiquer le nom de l'origine  externe ou laisser vide si origine interne", max_length=255, null=True, verbose_name='fournisseur externe'),
        ),
    ]
