# Generated by Django 2.0.6 on 2018-08-24 09:32

import datetime
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0022_auto_20180823_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='risque',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterField(
            model_name='controle',
            name='critere_cible',
            field=models.CharField(choices=[('S', 'Sévérité'), ('O', 'Occurence'), ('D', 'Détectabilité')], default='O', max_length=1, verbose_name='critère cible'),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 23, 9, 32, 13, 178567, tzinfo=utc), verbose_name='revue prevue pour le'),
        ),
        migrations.AddIndex(
            model_name='risque',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='risk_regist_search__991b31_gin'),
        ),
    ]
