# Generated by Django 2.0.6 on 2018-08-24 10:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('risk_register', '0024_auto_20180824_1043'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER risk_update_trigger
            BEFORE INSERT OR UPDATE OF nom, description, cause, consequence, couverture, pilotage, note, aide
            ON risk_register_risque
            FOR EACH ROW EXECUTE PROCEDURE 
            tsvector_update_trigger(search_vector, 'pg_catalog.french', nom, description, 
                                    cause, consequence, couverture, pilotage, note, aide);
            UPDATE risk_register_risque SET search_vector = NULL;
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS risk_update_trigger
            ON risk_register_risque
            """
        )
    ]
