# Generated by Django 2.0.6 on 2018-08-24 10:54

import datetime
import django.contrib.postgres.search
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0025_create_trigger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='risque',
            options={'ordering': ('created', 'nom', 'description'), 'verbose_name': 'risque', 'verbose_name_plural': 'risques'},
        ),
        migrations.AlterField(
            model_name='controle',
            name='critere_cible',
            field=models.CharField(choices=[('S', 'Sévérité'), ('D', 'Détectabilité'), ('O', 'Occurence')], default='O', max_length=1, verbose_name='critère cible'),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='date_revue',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 23, 10, 54, 15, 786053, tzinfo=utc), verbose_name='revue prevue pour le'),
        ),
        migrations.AlterField(
            model_name='risque',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
