# Generated by Django 2.0.6 on 2018-08-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0034_auto_20180829_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='critere_cible',
            field=models.CharField(choices=[('D', 'Détectabilité'), ('O', 'Occurence'), ('S', 'Sévérité')], default='O', max_length=1, verbose_name='critère cible'),
        ),
    ]
