# Generated by Django 2.0.6 on 2018-10-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0040_auto_20181008_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='critere_cible',
            field=models.CharField(choices=[('S', 'Sévérité'), ('D', 'Détectabilité'), ('O', 'Occurence')], default='O', max_length=1, verbose_name='critère cible'),
        ),
    ]
