# Generated by Django 2.0.6 on 2018-10-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0045_auto_20181010_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='critere_cible',
            field=models.CharField(choices=[('O', 'Occurence'), ('D', 'Détectabilité'), ('S', 'Sévérité')], default='O', max_length=1, verbose_name='critère cible'),
        ),
    ]
