# Generated by Django 2.0.6 on 2018-10-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0051_auto_20181012_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='critere_cible',
            field=models.CharField(choices=[('O', 'Occurence'), ('S', 'Sévérité'), ('D', 'Détectabilité')], default='O', max_length=1, verbose_name='critère cible'),
        ),
    ]
