# Generated by Django 2.0.6 on 2018-11-22 15:01

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0052_auto_20181012_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activiterisque',
            options={'get_latest_by': 'created', 'ordering': ('-created', 'verifie_le'), 'verbose_name': "risque d'activité", 'verbose_name_plural': 'risques des activités'},
        ),
        migrations.AlterField(
            model_name='activite',
            name='acheve_le',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', when={'completed'}),
        ),
        migrations.AlterField(
            model_name='activiterisque',
            name='verifie_le',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='verifie', when={'verified'}),
        ),
        migrations.AlterField(
            model_name='controle',
            name='critere_cible',
            field=models.CharField(choices=[('S', 'Sévérité'), ('D', 'Détectabilité'), ('O', 'Occurence')], default='O', max_length=1, verbose_name='critère cible'),
        ),
        migrations.AlterField(
            model_name='processusrisque',
            name='verifie_le',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='verifie', when={'verified'}),
        ),
    ]
