# Generated by Django 2.0.6 on 2018-11-24 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0058_auto_20181123_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='critere_cible',
            field=models.CharField(choices=[('S', 'Sévérité'), ('D', 'Détectabilité'), ('O', 'Occurence')], default='O', max_length=1, verbose_name='critère cible'),
        ),
        migrations.AlterField(
            model_name='risque',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risques', to='risk_register.ClasseDeRisques'),
        ),
        migrations.AlterField(
            model_name='risque',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risques_crees', to=settings.AUTH_USER_MODEL, verbose_name='Crée par'),
        ),
    ]
