# Generated by Django 2.0.6 on 2019-01-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0061_auto_20190121_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='critere_cible',
            field=models.CharField(choices=[('O', 'Occurence'), ('D', 'Détectabilité'), ('S', 'Sévérité')], default='O', max_length=1, verbose_name='critère cible'),
        ),
    ]
