# Generated by Django 2.0.6 on 2019-01-28 12:20

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0064_auto_20190123_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activiterisque',
            name='verifie_le',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='verifie', null=True, when={'verified'}),
        ),
        migrations.AlterField(
            model_name='controle',
            name='critere_cible',
            field=models.CharField(choices=[('S', 'Sévérité'), ('D', 'Détectabilité'), ('O', 'Occurence')], default='O', max_length=1, verbose_name='critère cible'),
        ),
        migrations.AlterField(
            model_name='processusrisque',
            name='verifie_le',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='verifie', null=True, when={'verified'}),
        ),
    ]
