from django.urls import path

from . import views

app_name = 'risk_register'

urlpatterns = [
    path('risks/<str:classe>/', views.RiskClassView.as_view(), name='liste_risques'),
    path('business-unit/<str:pk>/', views.BusinessUnitRiskRegisterView.as_view(), name='detail_business_unit'),
    path('process/<uuid:pk>/', views.ProcessusRiskRegisterView.as_view(), name='detail_processus'),
    path('activity/<uuid:pk>/', views.ActiviteRiskRegisterView.as_view(), name='detail_activite'),
    path('<str:business_unit>/create-process/', views.CreateProcessView.as_view(), name='creer_processus'),
    path('<uuid:pk>/update-process/', views.UpdateProcessView.as_view(), name='modifier_processus'),
    path('<uuid:processus>/create-process-input', views.CreateProcessInputView.as_view(), name='creer_entree'),
    path('<uuid:processus>/update-input-list/', views.AddProcessInputView.as_view(), name='ajout_entree'),
    path('<uuid:pk>/delete-process/', views.DeleteProcessView.as_view(), name='effacer_processus'),
    path('<uuid:processus>/add-activity/', views.CreateActiviteView.as_view(), name='creer_activite'),
    path('<uuid:pk>/update-activity/', views.UpdateActiviteView.as_view(), name='modifier_activite'),
    path('<uuid:pk>/delete-activity/', views.DeleteActiviteView.as_view(), name='effacer_activite'),
    path('<uuid:processus>/add-output/', views.CreateProcessOutputView.as_view(), name='ajout_sortie'),
    path('<uuid:processus>/add-risk-to-process/', views.AddProcessusrisqueView.as_view(), name='ajout_processusrisque'),
    path('<uuid:processus>/create-process-risk/', views.NewRiskForProcessView.as_view(), name='creer_risque_processus'),
    path('<uuid:pk>/detail-process-risk', views.ProcessusrisqueDetailview.as_view(), name='detail_processusrisque'),
    path('<uuid:processusrisque>/edit-process-risk/', views.EditProcessusrisqueView.as_view(),
         name='modifier_processusrisque'),
    path('<uuid:processusrisque>/delete-process-risk/', views.DeleteProcessusrisqueView.as_view(),
         name='effacer_processusrisque'),
    path('<uuid:activite>/add-risk-to-activity/', views.AddActiviterisqueView.as_view(), name='ajout_activiterisque'),
    path('<uuid:activite>/create-activity-risk/', views.NewRiskForActivityView.as_view(), name='creer_risque_activite'),
    path('<uuid:pk>/detail-activity-risk', views.ActiviterisqueDetailView.as_view(), name='detail_activiterisque'),
    path('risk-detail/<uuid:pk>/', views.RiskDetailView.as_view(), name='detail_risque'),
    path('risk-update/<uuid:pk>/', views.UpdateRiskView.as_view(), name='modifier_risque'),
    path('<uuid:activiterisque>/edit-activity-risk/', views.EditActiviterisqueView.as_view(),
         name='modifier_activiterisque'),
    path('<uuid:activiterisque>/delete-activity-risk/', views.DeleteActiviterisqueView.as_view(),
         name='effacer_activiterisque'),
    path('risque-autocomplete/', views.RiskAutocomplete.as_view(), name='risque-autocomplete'),
    path('<uuid:processusrisque>/add-control-process-risk/', views.AddProcessusrisqueControleView.as_view(),
         name='ajout_controle_processusrique'),
    path('<uuid:activiterisque>/add-control-activity-risk/', views.AddActiviterisqueControle.as_view(),
         name='ajout_controle_activiterisque'),
    path('<uuid:controle>/edit-control/', views.EditRiskControl.as_view(), name='modifier_controle'),
    path('<uuid:controle>/assign-control/', views.AssignerControleView.as_view(), name='assigner_controle'),
    path('<uuid:controle>/delete-control/', views.DeleteRiskControl.as_view(), name='effacer_controle'),
    path('<uuid:processusrisque>/set-seuil-processusrisque/', views.SetSeuilProcessusrisqueView.as_view(),
         name='definir_seuil_processusrisque'),
    path('<activiterisque>/set-seuil-activiterisque/', views.SetSeuilActiviterisqueView.as_view(),
         name='definir_seuil_activiterisque'),
    path('<uuid:processusrisque>/processusrisque-estimation/', views.ProcessusrisqueEstimationView.as_view(),
         name='estimer_processusrisque'),
    path('<uuid:activiterisque>/activiterisque-estimation', views.ActiviterisqueEstimationView.as_view(),
         name='estimer_activiterisque'),
    path('<uuid:activiterisque>/assign-activity-risk/', views.AssignerActiviterisqueView.as_view(),
         name='assigner-activiterisque'),
    path('<uuid:processusrisque>/assign-process-risk/', views.AssignerProcessusrisqueView.as_view(),
         name='assigner-processusrisque'),
    path('<uuid:processusrisque>/set-processusrisque-review-date/', views.SetProcessusrisqueReviewDate.as_view(),
         name='revue-processusrisque'),
    path('<uuid:activiterisque>/set-activiterisque-review-date/', views.SetActiviterisqueReviewDate.as_view(),
         name='revue-activiterisque'),
    path('ajax-risk-verification-status/<uuid:pk>/', views.check_risk_status, name='ajax-statut-risque'),
    path('ajax-control-completion-status/<uuid:pk>/', views.check_control_status, name='ajax-status-controle'),
    path('ajax-risk-verification-status-change/<uuid:pk>', views.change_risk_status, name='ajax-changer-statut-risque'),
    path('ajax-control-completion-status-change/<uuid:pk>/', views.change_control_status,
         name='ajax-changer-statut-controle'),
    path('ajax-approve-control/<uuid:pk>/', views.approve_controle, name='ajax-approuver-controle'),
    path('ajax-validate-control/<uuid:pk>/', views.validate_controle, name='ajax-validate-controle'),
    path('ajax-get-controle-validated/<uuid:pk>/', views.get_controle_est_valide, name='ajax-get-controle-valide'),
    path('ajax-get-controle-approved/<uuid:pk>/', views.get_controle_est_approuve, name='ajax-get-controle-approuve')
]
